logging:
  level: INFO


server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    port: 8080
    type: http

mongoHost : localhost
mongoPort : 27017
mongoDB : Dropwizard
collectionName: employees


#server:
#
#  applicationContextPath: /
#  applicationConnectors:
#  - type: http
#    port: 8999
#  adminConnectors:
#  - type: http
#    port: 8998
#
#logging:
#  level: INFO
#  loggers:
#    com.java: DEBUG
#
#mongoHost : localhost
#mongoPort : 27017
#mongoDB : softwaredevelopercentral
#collectionName: employees

